Repository 5weetMike/final-project-be, pull requests merged in 2024-10, with the labels that each got.

#4 bug: re-add function to find all
  src/users/controllers.js
  src/users/routes.js
Labels: chore

#7 enhancement: update user finsihed
  src/users/controllers.js
  src/users/routes.js
Labels: enhancement

#10 Enhancement: delete user finale
  src/users/controllers.js
  src/users/routes.js
Labels: enhancement

#11 Dev
  src/middleware/auth.js
  src/users/controllers.js
  src/users/routes.js
Labels: chore

#15 Cors update mh
  functions/api.js
  src/server.js
Labels: bug

#16 Dogs model dw
  src/dogs/controllers.js
  src/dogs/model.js
  src/dogs/routes.js
  src/server.js
  src/users/model.js
Labels: chore

#17 chore: edited netlify file
  netlify.toml
Labels: chore

#18 chore: cors
  functions/api.js
  src/server.js
Labels: chore

#20 Dog id dw
  src/dogs/controllers.js
  src/users/controllers.js
Labels: bug

#21 bug: error
  src/users/routes.js
Labels: bug

#23 bug-fix: missing comma
  src/users/controllers.js
Labels: chore
